language: go
sudo: false

services:
  - mysql

notifications:
  email: false

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - go vet ./...

go:
  - 1.4
  - 1.5
  - 1.6
  - tip
